name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release
        uses: softprops/action-gh-release@v1
  hexpm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "24.2"
          gleam-version: "nightly"
      - run: gleam format --check src test
      - run: gleam publish -y
