name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gleam: ["0.20.1", "0.21.0"]
        erlang: ["24.2"]
        node: ["16.14.2"]
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.erlang }}
          gleam-version: ${{ matrix.gleam }}
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: gleam format --check src test
      - run: gleam deps download
      - run: gleam test --target=erlang
      - run: gleam test --target=javascript
